package principal;


import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JDialog;
import javax.swing.JRadioButton;


/**
 * Fenêtre qui permet de définir les principales caractéristiques et des joueurs par défaut
 * @author Agustin Cartaya
 */
public class InitDlg extends javax.swing.JDialog {


    /**
     * Initialisation de la fenêtre, composants et variables
     * @param parent compossant parent
     * @param modal type d'ouverture
     * @param jeuMemory instance de la classe principale
     * @see LesPersonnages
     * @see LesJoueurs
     */
    public InitDlg(java.awt.Frame parent, boolean modal, JeuMemory jeuMemory) {
        super(parent, modal);
        initComponents();
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        this.jeuMemory = jeuMemory;
        //this.lp = lp;
        //this.lj = lj;
        this.niveau = 4;
        this.lj_v = new LesJoueurs();
        this.ok = false;
    }

    /**
     * revoie le niveau choisi
     * @return int avec le niveau choisi
     * @see LesPersonnages
     */
    public int getNiveau() {
        return niveau;
    }

    /**
     * revoyer les joueurs choisis 
     * @return variables types LesJoueurs avec les joueurs choisis
     * @see LesJoueurs
     */
    public LesJoueurs getJoueurs() {
        return lj_v;
    }

    /**
     * indique si la fenêtre est fermee en acceptant ou non les paramètres
     * @return true si les paramètres sont acceptées
     */
    public boolean isOk() {
        return ok;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        rbEnfant = new javax.swing.JRadioButton();
        rbDebutant = new javax.swing.JRadioButton();
        rbAvance = new javax.swing.JRadioButton();
        rbExpert = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        cbLara = new javax.swing.JCheckBox();
        cbJack = new javax.swing.JCheckBox();
        cbJeanSebastien = new javax.swing.JCheckBox();
        cbAmadeus = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDescription = new javax.swing.JTextArea();
        jbPhoto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btAnuler = new javax.swing.JButton();
        btValider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(730, 400));

        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choisissez la taille du jeu");
        jPanel4.add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel6.setLayout(new java.awt.GridLayout(4, 1));

        buttonGroup1.add(rbEnfant);
        rbEnfant.setSelected(true);
        rbEnfant.setText("enfant (4 personnaes, 2 familles)");
        rbEnfant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNiveauActionPerformed(evt);
            }
        });
        jPanel6.add(rbEnfant);

        buttonGroup1.add(rbDebutant);
        rbDebutant.setText("debutant (10 personnaes, 2 familles)");
        rbDebutant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNiveauActionPerformed(evt);
            }
        });
        jPanel6.add(rbDebutant);

        buttonGroup1.add(rbAvance);
        rbAvance.setText("avance (18 personnaes, 4 familles)");
        rbAvance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNiveauActionPerformed(evt);
            }
        });
        jPanel6.add(rbAvance);

        buttonGroup1.add(rbExpert);
        rbExpert.setText("expert (32 personnaes, 6 familles)");
        rbExpert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNiveauActionPerformed(evt);
            }
        });
        jPanel6.add(rbExpert);

        jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Choisissez les joueurs crees par defaut");
        jPanel5.add(jLabel2, java.awt.BorderLayout.NORTH);

        jPanel7.setLayout(new java.awt.GridLayout(4, 1));

        cbLara.setText("Lara");
        cbLara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJoueursParDafautActionPerformed(evt);
            }
        });
        jPanel7.add(cbLara);

        cbJack.setText("Jack");
        cbJack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJoueursParDafautActionPerformed(evt);
            }
        });
        jPanel7.add(cbJack);

        cbJeanSebastien.setText("Jean-Sebastien");
        cbJeanSebastien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJoueursParDafautActionPerformed(evt);
            }
        });
        jPanel7.add(cbJeanSebastien);

        cbAmadeus.setText("Amadeus");
        cbAmadeus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJoueursParDafautActionPerformed(evt);
            }
        });
        jPanel7.add(cbAmadeus);

        jPanel5.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5);

        jPanel3.setLayout(new java.awt.GridLayout(2, 1));

        jtaDescription.setColumns(20);
        jtaDescription.setRows(5);
        jScrollPane1.setViewportView(jtaDescription);

        jPanel3.add(jScrollPane1);

        jbPhoto.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel3.add(jbPhoto);

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        btAnuler.setText("Anueler");
        btAnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnulerActionPerformed(evt);
            }
        });
        jPanel2.add(btAnuler);

        btValider.setText("Valider");
        btValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValiderActionPerformed(evt);
            }
        });
        jPanel2.add(btValider);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * ferme la fenêtre sans enregistrer les modifications
     * @param evt source de l'événement
     */
    private void btAnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_btAnulerActionPerformed

    /**
     * Actions des RadioButtons qui controlent
     * les niveuax du jeu
     * @param evt source de l'événement
     */
    private void rbNiveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNiveauActionPerformed
        JRadioButton rb = (JRadioButton)evt.getSource();
        
        if(rb.equals(this.rbEnfant))
            this.niveau = 4;
        else if(rb.equals(this.rbDebutant))
            this.niveau = 4;
        else if(rb.equals(this.rbAvance))
            this.niveau = 18;
        else if(rb.equals(this.rbExpert))
            this.niveau = 32;
        
    }//GEN-LAST:event_rbNiveauActionPerformed

    /**
     * Actions des checkBox qui ajoutent les joueurs
     * par defaut
     * @param evt source de l'événement
     */
    private void cbJoueursParDafautActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJoueursParDafautActionPerformed
        JCheckBox rb = (JCheckBox)evt.getSource();
        Joueur j= null;
        
        //le joueur du checkBox sélectionné est créé
        if(rb.equals(this.cbLara))
            j =new Joueur("Lara", "epiques");

        else if(rb.equals(this.cbJack))
            j =new Joueur("Jack", "rares");

        else if(rb.equals(this.cbJeanSebastien))
            j =new Joueur("Jean-Sébastien", "alpins-femmes");

        else if(rb.equals(this.cbAmadeus))
            j =new Joueur("Amadeus", "communs");
        
        //si le check a ete sélectionné le joueur s'ajoute a la liste provisoire
        //sinon le joueur est supprimé de la liste
        if(rb.isSelected()){
            j.setPhoto(new ImageIcon( getSrcImage(j.getPseudo()) ));
            this.lj_v.ajouteJoueur(j);
        }else{
            this.lj_v.supprimeJoueur(j.getPseudo());
        }
        //l'information du dernier joueur de la liste est montree
        //de cette maniere un effet de memoire est fait quand les check sont selectione ou deselectione
        //s'il y a pas des joueur dans la liste provisoire totes les informations ainsi que l'image est efface
        if(this.lj_v.getNbJoueurs()>0){
            j = lj_v.getJoueur( lj_v.getNbJoueurs()-1 );
            this.jtaDescription.setText(j.toString());
            j.setImgBouton(jbPhoto);
           
        }else{
            this.jtaDescription.setText("");
            this.jbPhoto.setIcon(null);
        }
        
    }//GEN-LAST:event_cbJoueursParDafautActionPerformed

    /**
     * Établit les paramètre initiaux du jeu
     * avec une quantité des personnages selon la difficulté
     * ainsi que les joueurs par défaut
     * si tout se passe bien, la fenêtre est fermé
     * @param evt source de l'événement
     */
    private void btValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValiderActionPerformed
//        this.lp = new LesPersonnages(niveau);
//        this.lj.ajouteJoueurs(lj_v);
        this.jeuMemory.setPrincipalParametres(lj_v, new LesPersonnages(niveau));
        this.ok = true;
        this.dispose();
    }//GEN-LAST:event_btValiderActionPerformed

    /**
     * Renvoie l'URL de l'image du personnage de nom p
     * utilisé pour simplifier certaines lignes de code
     * @param p nom du personnage
     * @return String avec l'URL de l'image
     */
    public static String getSrcImage(String p){
        String s = "src/img/";
        switch(p){
            case "Lara":
                s += "lara.jpg";
                break;
            case "Jack":
                s += "jack.png";
                break;
            case "Jean-Sébastien":
                s += "mozart.jpg";
                break;
            case "Amadeus":
                s += "bach.jpg";
                break;
        }
        return s;
    }
    
//    private LesPersonnages lp;
//    private LesJoueurs lj;
    private JeuMemory jeuMemory;
    private int niveau;
    private LesJoueurs lj_v;
    private boolean ok;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnuler;
    private javax.swing.JButton btValider;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbAmadeus;
    private javax.swing.JCheckBox cbJack;
    private javax.swing.JCheckBox cbJeanSebastien;
    private javax.swing.JCheckBox cbLara;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbPhoto;
    private javax.swing.JTextArea jtaDescription;
    private javax.swing.JRadioButton rbAvance;
    private javax.swing.JRadioButton rbDebutant;
    private javax.swing.JRadioButton rbEnfant;
    private javax.swing.JRadioButton rbExpert;
    // End of variables declaration//GEN-END:variables
}
