package principal;


import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * Fenêtre qui permet ajoueter un nouvau joueur
 * @author Agustin Cartaya
 */
public class SaisieJoueurDlg extends javax.swing.JDialog {

    /**
     * Initialisation de la fenêtre, composants et variables
     * @param parent compossant parent
     * @param modal type d'ouverture
     * @param lj instance de la liste de joueurs
     * @see LesJoueurs
     */
    public SaisieJoueurDlg(java.awt.Frame parent, boolean modal,  LesJoueurs lj) {
        super(parent, modal);
        initComponents();
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        this.lj = lj;
        this.dlm = new DefaultListModel();
        this.ltFamilles.setModel(this.dlm);
        initListeFamilles();
    }
    
    /**
     * indique si la fenêtre est fermee en acceptant ou non les paramètres
     * @return true si les paramètres sont acceptées
     */
    public boolean isOk() {
        return ok;
    }

    /**
     * Revoie le nouveau joueur cree
     * @return joueur cree
     * @see Joueur
     */
    public Joueur getNewJoueur() {
        return newJoueur;
    }
    
    /**
     * Remplit la liste avec toutes les familles existantes
     */
    private void initListeFamilles(){
        //une instance de type Les Personnages est créée pour obtenir toutes le familles existents
        for(String nomFamille: (new LesPersonnages(32)).getFamilles())
            this.dlm.addElement(nomFamille);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfPseudo = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ltFamilles = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btParcourrir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btPhoto = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btAnnuler = new javax.swing.JButton();
        btValider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Creez votre joueur !");
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Donnez votre pseudo:");
        jPanel4.add(jLabel2, java.awt.BorderLayout.NORTH);
        jPanel4.add(tfPseudo, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Quelle est votre famille prefere de personnages?");
        jPanel5.add(jLabel3, java.awt.BorderLayout.NORTH);

        jScrollPane1.setViewportView(ltFamilles);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Choisissez une photo:");
        jPanel6.add(jLabel4, java.awt.BorderLayout.NORTH);

        btParcourrir.setText("Parcourrir");
        btParcourrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btParcourrirActionPerformed(evt);
            }
        });
        jPanel6.add(btParcourrir, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel6);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel3.add(btPhoto, java.awt.BorderLayout.CENTER);

        jPanel7.setLayout(new java.awt.GridLayout(1, 2));

        btAnnuler.setText("Annuler");
        btAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnnulerActionPerformed(evt);
            }
        });
        jPanel7.add(btAnnuler);

        btValider.setText("Valider");
        btValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValiderActionPerformed(evt);
            }
        });
        jPanel7.add(btValider);

        jPanel3.add(jPanel7, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Action du bouton "Parcourrir" qui ouvre un JFileChooser
     * pour obtenir l'URL de l'image du joueur
     * @param evt source de l'événement
     */
    private void btParcourrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btParcourrirActionPerformed
        JFileChooser jf= new JFileChooser("./src/img");
        if (jf.showOpenDialog(this)== JFileChooser.APPROVE_OPTION)
        {
            String path = jf.getSelectedFile().getPath();
            Image img=Toolkit.getDefaultToolkit().getImage(path);
            img=img.getScaledInstance(btPhoto.getWidth()-10, btPhoto.getHeight()-10, Image.SCALE_DEFAULT);
            ImageIcon photo1 = new ImageIcon(img);
            btPhoto.setIcon(photo1);
        } 
    }//GEN-LAST:event_btParcourrirActionPerformed

    /**
     * ferme la fenêtre sans enregistrer les modifications
     * @param evt source de l'événement
     */
    private void btAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnnulerActionPerformed
       this.dispose();
    }//GEN-LAST:event_btAnnulerActionPerformed

    /**
     * verifie que tous les champs nécessaires sont remplis
     * correptement et si c'est le cas, ajoute le joueur a la liste de joueurs,
     * sinon une erreur est affiché en forme de fenêtre contextuelle
     * après la fenêtre est fermé
     * @param evt source de l'événement
     * @see LesJoueurs#ajouteJoueur(principal.Joueur) 
     */
    private void btValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValiderActionPerformed
        if(this.tfPseudo.getText() != null && !this.tfPseudo.getText().equals("")
            && this.ltFamilles.getSelectedIndex() != -1
            && this.btPhoto.getIcon()!= null ){
            
                this.newJoueur = new Joueur(this.tfPseudo.getText(),
                this.dlm.getElementAt( this.ltFamilles.getSelectedIndex()).toString());
                this.newJoueur.setPhoto( (ImageIcon)this.btPhoto.getIcon() );
                this.newJoueur.initPaquetTest();
                this.lj.ajouteJoueur(this.newJoueur);
                this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "SVP saisir les informations nécessaires ",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
            
    }//GEN-LAST:event_btValiderActionPerformed



    //reference à la liste de joueurs
    private LesJoueurs lj;
    
    //modele par de la liste
    private DefaultListModel dlm;
    
    //reference au nouveau joueur
    private Joueur newJoueur;
    
    private LesPersonnages lp;//non utilise
    private boolean ok;//non utilise
    private ImageIcon photo;//non utilise
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnnuler;
    private javax.swing.JButton btParcourrir;
    private javax.swing.JButton btPhoto;
    private javax.swing.JButton btValider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> ltFamilles;
    private javax.swing.JTextField tfPseudo;
    // End of variables declaration//GEN-END:variables
}
